apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      resolver 10.0.0.10 valid=30s;

      upstream app1 {
        server app1-service:8080;
      }

      upstream app2 {
        server app2-service:8080;
      }

      server {
        listen 80;

        location /app1 {
          proxy_pass http://app1;
          proxy_set_header Host $host;
        }

        location /app2 {
          proxy_pass http://app2;
          proxy_set_header Host $host;
        }
      }
    }
